# Generated by Django 6.0.3 on 2026-04-17 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(help_text='A chave única enviada pelo cliente (ex: UUID)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Usado como trava para evitar processamento simultâneo', null=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_data',
            field=models.JSONField(blank=True, help_text='A resposta salva para ser retornada se houver repetição', null=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='O usuário que fez a requisição', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
