services:
  - type: web
    name: octobox-control
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi --log-file -
    preDeployCommand: python manage.py migrate && python manage.py bootstrap_roles
    healthCheckPath: /api/v1/health/
    autoDeploy: true
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: octobox-control-db
          property: connectionString
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: octobox-control-db
    plan: starter