# Generated by Django 6.0.4 on 2026-05-07 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('box_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('plan', models.CharField(choices=[('monthly', 'Mensal R$ 97'), ('annual', 'Anual R$ 997')], default='annual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pagamento confirmado'), ('activated', 'Conta ativada'), ('canceled', 'Cancelado pelo cliente'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('magic_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('magic_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('landing_referer', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Anotacoes manuais do operador (WhatsApp, follow-up, etc).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_signup_origin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro pendente',
                'verbose_name_plural': 'Cadastros pendentes (Early Adopters)',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='signup_pend_status_118839_idx'), models.Index(fields=['plan', 'status'], name='signup_pend_plan_c40801_idx')],
            },
        ),
    ]
