# Generated by Django 6.0.8 on 2026-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Codigo de campanha vindo do link de divulgacao (?promo=...), normalizado em maiusculas.', max_length=32),
        ),
    ]
