"""
ARQUIVO: migration 0002 de onboarding e comunicacao via WhatsApp.

POR QUE ELE EXISTE:
- registra no banco a introducao das entidades de intake, contatos WhatsApp e log de mensagens.

O QUE ESTE ARQUIVO FAZ:
1. cria a tabela de captacao inicial de alunos.
2. cria a tabela de contatos WhatsApp vinculaveis a alunos.
3. cria a tabela de historico de mensagens para rastreabilidade operacional.

PONTOS CRITICOS:
- migrations fazem parte do historico do schema e nao devem ser reescritas sem necessidade real.
- alteracoes aqui podem quebrar ambientes ja migrados ou restauracoes antigas.
"""

# Generated by Django 6.0.3 on 2026-03-10 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('whatsapp', 'WhatsApp'), ('import', 'Importação externa')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('reviewing', 'Em revisão'), ('matched', 'Vinculado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='new', max_length=16)),
                ('raw_payload', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intakes', to=settings.AUTH_USER_MODEL)),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_records', to='boxcore.student')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('linked', 'Vinculado'), ('opted_out', 'Sem consentimento')], default='new', max_length=16)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to='boxcore.student')),
            ],
            options={
                'ordering': ['display_name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Saída')], default='inbound', max_length=16)),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('template', 'Template'), ('interactive', 'Interativa'), ('system', 'Sistema')], default='text', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('external_message_id', models.CharField(blank=True, max_length=120)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='boxcore.whatsappcontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
