"""
ARQUIVO: migration 0003 de auditoria operacional.

POR QUE ELE EXISTE:
- adiciona a trilha de auditoria persistente para registrar quem fez o que no sistema.

O QUE ESTE ARQUIVO FAZ:
1. cria a tabela de eventos de auditoria.
2. relaciona evento com usuario ator quando disponivel.
3. define ordenacao por eventos mais recentes primeiro.

PONTOS CRITICOS:
- qualquer mudanca nesta migration afeta consistencia do historico de auditoria entre ambientes.
- ajustes retroativos em migrations antigas exigem cuidado com bancos ja existentes.
"""

# Generated by Django 6.0.3 on 2026-03-10 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0002_studentintake_whatsappcontact_whatsappmessagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(max_length=80)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
