# Generated by Django 6.0.3 on 2026-03-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0006_integration_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='webhook_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='external_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('webhook_fingerprint', ''), _negated=True), fields=('webhook_fingerprint',), name='unique_non_blank_whatsapp_webhook_fingerprint'),
        ),
    ]
