# Generated by Django 6.0.3 on 2026-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0007_whatsappmessagelog_webhook_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluido'), ('failed', 'Falha')], db_index=True, default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('expired', 'Expirada'), ('canceled', 'Cancelada')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('canceled', 'Cancelado'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('active', 'Ativo'), ('paused', 'Pausado'), ('inactive', 'Inativo')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('reviewing', 'Em revisão'), ('matched', 'Vinculado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], db_index=True, default='new', max_length=16),
        ),
    ]
