# Generated by Django 6.0.3 on 2026-03-26 07:57

import shared_support.crypto_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0008_asyncjob_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Controle de concorrência otimista'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=shared_support.crypto_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=shared_support.crypto_fields.EncryptedCharField(max_length=255, unique=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='email',
            field=shared_support.crypto_fields.EncryptedCharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='phone',
            field=shared_support.crypto_fields.EncryptedCharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='phone',
            field=shared_support.crypto_fields.EncryptedCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='body',
            field=shared_support.crypto_fields.EncryptedTextField(blank=True),
        ),
    ]
