# Generated by Django 6.0.3 on 2026-03-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0009_payment_version_alter_student_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditevent',
            table='boxcore_auditevent',
        ),
    ]
