# Generated by Django 6.0.3 on 2026-03-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0010_alter_auditevent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_lookup_index',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='studentintake',
            name='phone_lookup_index',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='phone_lookup_index',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
