# Generated by Django 6.0.3 on 2026-03-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0012_backfill_blind_indices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_lookup_index', ''), _negated=True), fields=('phone_lookup_index',), name='unique_non_blank_student_phone_lookup_index'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_lookup_index', ''), _negated=True), fields=('phone_lookup_index',), name='unique_non_blank_whatsapp_phone_lookup_index'),
        ),
    ]
