# Generated by Django 6.0.3 on 2026-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0019_financefollowup_suggestion_window_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='source_resolution_method',
            field=models.CharField(blank=True, choices=[('', 'Nao definido'), ('intake_auto', 'Intake automatico'), ('manual_form', 'Formulario manual'), ('manual_review', 'Revisao manual'), ('declared_only', 'Somente declarado'), ('legacy', 'Legado')], max_length=24),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('csv', 'Indicacao'), ('whatsapp', 'WhatsApp'), ('import', 'Importacao externa')], default='manual', max_length=16),
        ),
    ]
