# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0020_alter_student_source_resolution_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncjob',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='created_by_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='job_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='last_failure_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
