# Generated by Codex on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0021_asyncjob_signal_mesh_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('whatsapp_list', 'Lista do WhatsApp'), ('tecnofit_export', 'Exportacao Tecnofit'), ('nextfit_export', 'Exportacao Nextfit'), ('iphone_vcf', 'VCF - iPhone')], db_index=True, max_length=32)),
                ('declared_range', models.CharField(choices=[('up_to_200', 'Ate 200'), ('from_201_to_500', '201 a 500'), ('from_501_to_2000', '501 a 2000')], db_index=True, max_length=24)),
                ('processing_mode', models.CharField(choices=[('sync', 'Processamento imediato'), ('async_now', 'Background imediato'), ('async_night', 'Agendamento noturno')], db_index=True, default='sync', max_length=16)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('validating', 'Validando'), ('queued', 'Na fila'), ('scheduled', 'Agendado'), ('running', 'Processando'), ('completed', 'Concluido'), ('completed_with_warnings', 'Concluido com alertas'), ('rejected', 'Rejeitado'), ('failed', 'Falha')], db_index=True, default='received', max_length=32)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('detected_lead_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('duplicate_details', models.JSONField(blank=True, default=list)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
