# Generated by Django 6.0.3 on 2026-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0022_lead_import_job_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execucao'), ('completed', 'Concluido'), ('failed', 'Falha')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('csv', 'Indicação'), ('whatsapp', 'WhatsApp'), ('import', 'Importação externa')], default='manual', max_length=16),
        ),
    ]
