# Generated by Django 6.0.4 on 2026-05-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0025_classsession_status_time_index'),
        ('student_identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_identity.studentidentity'),
        ),
    ]
