# Generated by Django 6.0.6 on 2026-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0026_sprint2_student_identity_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='brl', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
