# Generated by Django 6.0.8 on 2026-09-02 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0029_backfill_intake_outcome_markers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='behaviornote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='behavior_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financefollowup',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_finance_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadimportjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='source_captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='captured_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsourcedeclaration',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='captured_student_source_declarations', to=settings.AUTH_USER_MODEL),
        ),
    ]
