# Generated by Django 6.0.8 on 2026-09-28 23:33

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_PROGRAMS = (
    ('crossfit', 'CrossFit', ['warmup', 'strength', 'skill', 'metcon', 'cooldown', 'mobility', 'custom']),
    ('hyrox', 'HYROX', ['warmup', 'strength', 'skill', 'metcon', 'cooldown', 'mobility', 'custom']),
    ('mobility', 'Alongamento e mobilidade', ['warmup', 'cooldown', 'mobility', 'custom']),
    ('oly', 'Halterofilia', ['warmup', 'skill', 'cooldown', 'custom']),
    ('strength', 'Força', ['warmup', 'strength', 'skill', 'cooldown', 'custom']),
    ('open_gym', 'Open Gym', ['warmup', 'strength', 'skill', 'metcon', 'cooldown', 'mobility', 'custom']),
    ('other', 'Outros', ['warmup', 'strength', 'skill', 'metcon', 'cooldown', 'mobility', 'custom']),
)


def seed_workout_programs(apps, schema_editor):
    WorkoutProgram = apps.get_model('boxcore', 'WorkoutProgram')
    ClassSession = apps.get_model('boxcore', 'ClassSession')
    manager = WorkoutProgram.objects.using(schema_editor.connection.alias)
    programs = {}
    for sort_order, (slug, name, allowed_block_kinds) in enumerate(DEFAULT_PROGRAMS):
        program, _created = manager.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'allowed_block_kinds': allowed_block_kinds,
                'sort_order': sort_order,
            },
        )
        programs[slug] = program

    class_type_to_program = {
        'cross': 'crossfit',
        'hyrox': 'hyrox',
        'mobility': 'mobility',
        'oly': 'oly',
        'strength': 'strength',
        'open_gym': 'open_gym',
        'other': 'other',
    }
    sessions = ClassSession.objects.using(schema_editor.connection.alias).all().only('id', 'class_type', 'title')
    for session in sessions.iterator(chunk_size=500):
        title = (session.title or '').strip().lower()
        program_slug = 'hyrox' if 'hyrox' in title else class_type_to_program.get(session.class_type, 'other')
        update_values = {
            'workout_program_id': programs[program_slug].pk,
        }
        if program_slug == 'hyrox' and session.class_type != 'hyrox':
            update_values['class_type'] = 'hyrox'
        ClassSession.objects.using(schema_editor.connection.alias).filter(pk=session.pk).update(**update_values)


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0030_alter_auditevent_actor_alter_behaviornote_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('allowed_block_kinds', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='classsession',
            name='class_type',
            field=models.CharField(choices=[('cross', 'CrossFit'), ('hyrox', 'HYROX'), ('mobility', 'Mobilidade / Alongamento'), ('oly', 'Halterofilia'), ('strength', 'Forca'), ('open_gym', 'Open Gym'), ('other', 'Outro')], db_index=True, default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='classsession',
            name='workout_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='boxcore.workoutprogram'),
        ),
        migrations.RunPython(seed_workout_programs, migrations.RunPython.noop),
    ]
