# Generated by Django 6.0.4 on 2026-04-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInvitationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou')], db_index=True, max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='student_identity.studentappinvitation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invitation_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
