# Generated by Django 5.2.1 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentappinvitation',
            name='invite_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('open_box', 'Box com aprovação')], db_index=True, default='individual', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentappinvitation',
            name='onboarding_journey',
            field=models.CharField(choices=[('mass_box_invite', 'Link em massa do box'), ('imported_lead_invite', 'Lead importado'), ('registered_student_invite', 'Aluno já cadastrado')], db_index=True, default='registered_student_invite', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentboxmembership',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Aguardando aprovação'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended_financial', 'Suspenso financeiro'), ('revoked', 'Revogado'), ('expired', 'Expirado')], db_index=True, default='pending_approval', max_length=24),
        ),
        migrations.AlterField(
            model_name='studenttransfer',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], db_index=True, default='requested', max_length=16),
        ),
    ]
