# Generated by Django 6.0.6 on 2026-06-23 05:07

import django.db.models.deletion
import django.utils.timezone
import student_identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('student_identity', '0002_alter_studentappinvitation_invite_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentboxmembership',
            name='clearance_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='studentboxmembership',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentboxmembership',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_student_box_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('waiver', 'Termo de responsabilidade'), ('parq', 'PAR-Q')], db_index=True, max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['kind', '-effective_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='unique_consent_document_kind_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kind',), name='unique_active_consent_document_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='StudentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_root_slug', models.CharField(db_index=True, default=student_identity.models._default_box_root_slug, max_length=64)),
                ('document_kind', models.CharField(choices=[('waiver', 'Termo de responsabilidade'), ('parq', 'PAR-Q')], db_index=True, max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('parq_outcome', models.CharField(blank=True, choices=[('clear', 'Sem risco'), ('flagged', 'Risco sinalizado')], max_length=16)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_consents', to='control.box')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='student_identity.studentidentity')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('identity', 'box_root_slug', 'document_kind', 'version'), name='unique_student_consent_identity_box_kind_version')],
            },
        ),
    ]
