# Generated by Django 6.0.4 on 2026-04-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0002_studentinvitationdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinvitationdelivery',
            name='status',
            field=models.CharField(
                choices=[
                    ('sent', 'Enviado'),
                    ('failed', 'Falhou'),
                    ('delivered', 'Entregue'),
                    ('delayed', 'Atrasado'),
                    ('bounced', 'Bounce'),
                    ('complained', 'Reclamado'),
                    ('suppressed', 'Suprimido'),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='StudentInvitationDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='student_identity.studentinvitationdelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
