# Generated by Django 6.0.8 on 2026-09-13 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_identity", "0003_studentboxmembership_clearance_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWorkoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "student_identity_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="studentconsent",
            name="document_kind",
            field=models.CharField(
                choices=[
                    ("waiver", "Termo de responsabilidade"),
                    ("parq", "PAR-Q"),
                    ("health_data", "Dado de saude"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="studentconsentdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waiver", "Termo de responsabilidade"),
                    ("parq", "PAR-Q"),
                    ("health_data", "Dado de saude"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PublicWorkoutLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_tokens",
                        to="student_identity.publicworkoutaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
