# Generated by Django 6.0.3 on 2026-04-17 03:16

import django.db.models.deletion
import student_identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0021_asyncjob_signal_mesh_fields'),
        ('student_identity', '0003_delivery_event_and_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidentity',
            name='primary_box_root_slug',
            field=models.CharField(db_index=True, default=student_identity.models._default_box_root_slug, max_length=64),
        ),
        migrations.CreateModel(
            name='StudentBoxMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_root_slug', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending_approval', 'Aguardando aprovacao'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended_financial', 'Suspenso financeiro'), ('revoked', 'Revogado'), ('expired', 'Expirado')], db_index=True, default='pending_approval', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_box_memberships', to=settings.AUTH_USER_MODEL)),
                ('created_from_invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_created', to='student_identity.studentappinvitation')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_identity.studentidentity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_memberships', to='boxcore.student')),
            ],
            options={
                'ordering': ['student__full_name', 'box_root_slug'],
                'constraints': [models.UniqueConstraint(fields=('identity', 'box_root_slug'), name='unique_student_membership_per_identity_box')],
            },
        ),
    ]
