# Generated by Django 6.0.8 on 2026-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_identity", "0003_studentboxmembership_clearance_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentconsent",
            name="document_kind",
            field=models.CharField(
                choices=[
                    ("waiver", "Termo de responsabilidade"),
                    ("parq", "PAR-Q"),
                    ("health_data", "Dado de saude"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="studentconsentdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waiver", "Termo de responsabilidade"),
                    ("parq", "PAR-Q"),
                    ("health_data", "Dado de saude"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
