# Generated by Django 6.0.8 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_identity", "0004_publicworkoutaccount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWorkoutLocalStorageBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_slug", models.CharField(db_index=True, max_length=50)),
                ("store_key", models.CharField(blank=True, max_length=100)),
                ("raw_blob", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan_slug", "-created_at"],
                        name="student_ide_plan_sl_4183e4_idx",
                    )
                ],
            },
        ),
    ]
