# Generated by Django 6.0.3 on 2026-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0004_studentidentity_primary_box_root_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappinvitation',
            name='invite_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('open_box', 'Box com aprovacao')], db_index=True, default='individual', max_length=16),
        ),
    ]
