# Generated by Django 6.0.3 on 2026-04-18 22:08

import django.db.models.deletion
import student_identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0005_studentappinvitation_invite_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappinvitation',
            name='onboarding_journey',
            field=models.CharField(choices=[('mass_box_invite', 'Link em massa do box'), ('imported_lead_invite', 'Lead importado'), ('registered_student_invite', 'Aluno ja cadastrado')], db_index=True, default='registered_student_invite', max_length=32),
        ),
        migrations.CreateModel(
            name='StudentBoxInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('box_root_slug', models.CharField(db_index=True, default=student_identity.models._default_box_root_slug, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_uses', models.PositiveIntegerField(default=200)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_box_invite_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
