# Generated by Django 6.0.4 on 2026-04-23 00:00

import django.db.models.deletion
import django.utils.timezone
import student_identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_identity', '0006_studentappinvitation_onboarding_journey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_root_slug', models.CharField(db_index=True, default=student_identity.models._default_box_root_slug, max_length=64)),
                ('endpoint', models.CharField(db_index=True, max_length=500, unique=True)),
                ('subscription', models.JSONField(blank=True, default=dict)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='student_identity.studentidentity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
