# Generated by Django 6.0.4 on 2026-05-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('student_identity', '0008_merge_0007_push_and_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentboxmembership',
            options={'ordering': ['box_root_slug']},
        ),
        migrations.AlterModelOptions(
            name='studentidentity',
            options={'ordering': ['student_name']},
        ),
        migrations.RemoveField(
            model_name='studentappinvitation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentboxmembership',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentidentity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studenttransfer',
            name='student',
        ),
        migrations.AddField(
            model_name='studentappinvitation',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invitations', to='control.box'),
        ),
        migrations.AddField(
            model_name='studentappinvitation',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentappinvitation',
            name='student_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentboxinvitelink',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invite_links', to='control.box'),
        ),
        migrations.AddField(
            model_name='studentboxmembership',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_memberships', to='control.box'),
        ),
        migrations.AddField(
            model_name='studentboxmembership',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_identities', to='control.box'),
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='primary_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_student_identities', to='control.box'),
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentidentity',
            name='student_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentpushsubscription',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_push_subscriptions', to='control.box'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='from_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='control.box'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='to_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='control.box'),
        ),
    ]
