# Generated by Django 6.0.3 on 2026-04-17 07:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxcore', '0022_lead_import_job_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(db_index=True, max_length=120)),
                ('default_unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'usage_count'], name='qs_tpl_active_usage_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name',), name='uq_quick_product_template_normalized_name')],
            },
        ),
        migrations.CreateModel(
            name='QuickProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(max_length=120)),
                ('normalized_alias_name', models.CharField(db_index=True, max_length=120)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='quick_sales.quickproducttemplate')),
            ],
            options={
                'ordering': ['alias_name'],
                'constraints': [models.UniqueConstraint(fields=('normalized_alias_name',), name='uq_quick_product_alias_normalized_name')],
            },
        ),
        migrations.CreateModel(
            name='QuickSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typed_description', models.CharField(max_length=120)),
                ('normalized_description', models.CharField(db_index=True, max_length=120)),
                ('resolved_description', models.CharField(max_length=120)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('bank_slip', 'Boleto'), ('transfer', 'Transferência'), ('other', 'Outro')], default='pix', max_length=16)),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('canceled', 'Cancelado'), ('refunded', 'Estornado')], db_index=True, default='paid', max_length=24)),
                ('resolution_mode', models.CharField(choices=[('exact_template', 'Template exato'), ('exact_alias', 'Alias exato'), ('fuzzy_match', 'Sugestao aproximada'), ('manual', 'Manual')], db_index=True, default='manual', max_length=24)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('sold_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_sales', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_sales', to='boxcore.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='quick_sales.quickproducttemplate')),
            ],
            options={
                'ordering': ['-sold_at', '-created_at'],
                'indexes': [models.Index(fields=['student', '-sold_at'], name='qs_sale_student_sold_idx'), models.Index(fields=['student', 'status'], name='qs_sale_student_status_idx')],
            },
        ),
    ]
