# Generated by Django 6.0.8 on 2026-09-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWorkoutAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_slug', models.CharField(db_index=True, max_length=50)),
                ('measured_at', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('body_fat_source', models.CharField(blank=True, max_length=20)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_workout_assessments',
                'ordering': ['plan_slug', 'measured_at'],
                'indexes': [models.Index(fields=['plan_slug', 'measured_at'], name='public_work_plan_sl_87d267_idx')],
            },
        ),
    ]
