# Generated by Django 6.0.8 on 2026-09-13 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWorkoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('student_identity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicWorkoutLocalStorageBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_slug', models.CharField(db_index=True, max_length=50)),
                ('store_key', models.CharField(blank=True, max_length=100)),
                ('raw_blob', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan_slug', '-created_at'], name='public_work_plan_sl_5af821_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicWorkoutLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to='public_workouts.publicworkoutaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
