# Generated by Django 6.0.8 on 2026-09-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWorkoutMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("label_pt", models.CharField(max_length=160)),
                ("label_en", models.CharField(blank=True, max_length=160)),
                ("reference_url", models.URLField(blank=True, max_length=255)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("crossfit", "CrossFit"),
                            ("strength", "Musculacao"),
                            ("both", "Ambos"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "movement_pattern",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("pending", "Pendente de revisao"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="publicworkoutassessment",
            name="student_identity_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
