# Generated by Django 6.0.8 on 2026-09-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0002_publicworkoutaccount_publicworkoutlocalstoragebackup_and_more'),
        ('public_workouts', '0002_publicworkoutmovement_and_more'),
    ]

    operations = [
    ]
