# Generated by Django 6.0.8 on 2026-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_workouts", "0002_publicworkoutmovement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWorkoutProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=50)),
                ("program_id", models.CharField(db_index=True, max_length=80)),
                ("program_label", models.CharField(max_length=160)),
                ("started_on", models.DateField()),
                ("weeks", models.PositiveSmallIntegerField()),
                ("version", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program_id", "version"),
                        name="unique_public_workout_program_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("slug",),
                        name="unique_active_public_workout_program_per_slug",
                    ),
                ],
            },
        ),
    ]
