# Generated by Django 6.0.8 on 2026-09-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0003_merge_20260913_2030'),
        ('public_workouts', '0003_publicworkoutprogram'),
    ]

    operations = [
    ]
