# Generated by Django 6.0.8 on 2026-09-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0003_publicworkoutsubscription_publicworkoutpayment_and_more'),
        ('public_workouts', '0004_merge_20260913_2041'),
    ]

    operations = [
    ]
