# Generated by Django 6.0.8 on 2026-09-14 00:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_workouts", "0005_merge_20260913_2051"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWorkoutLoadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_slug", models.SlugField(max_length=80)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rir",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("performed_on", models.DateField(db_index=True)),
                ("program_id", models.CharField(blank=True, max_length=80)),
                ("week_in_program", models.PositiveIntegerField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_logs",
                        to="public_workouts.publicworkoutaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "movement_slug", "performed_on"],
                        name="public_work_account_c5a7a3_idx",
                    )
                ],
            },
        ),
    ]
