# Generated by Django 6.0.8 on 2026-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0006_publicworkoutloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutsubscription',
            name='tier',
            field=models.CharField(choices=[('essencial', 'Essencial'), ('completo', 'Completo'), ('premium', 'Premium')], db_index=True, default='essencial', max_length=16),
        ),
        migrations.AlterField(
            model_name='publicworkoutsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('past_due', 'Em atraso'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada'), ('pending_payment', 'Aguardando pagamento')], db_index=True, default='active', max_length=16),
        ),
    ]
