# Generated by Django 6.0.8 on 2026-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0006_publicworkoutloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutaccount',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
