# Generated by Django 6.0.8 on 2026-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0007_publicworkoutsubscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicworkoutsubscription',
            name='plan_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='publicworkoutsubscription',
            index=models.Index(condition=models.Q(('plan_slug__isnull', False)), fields=['plan_slug'], name='pw_sub_plan_slug_not_null_idx'),
        ),
    ]
