# Generated by Django 6.0.8 on 2026-09-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0008_publicworkoutsubscription_plan_slug_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWorkoutProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('treino', 'Treino'), ('nutricao', 'Nutrição')], max_length=16)),
                ('registration_council', models.CharField(max_length=16)),
                ('registration_number', models.CharField(max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicWorkoutNutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comorbidades', models.TextField(blank=True)),
                ('alergias_restricoes', models.TextField(blank=True)),
                ('rotina_alimentar', models.TextField(blank=True)),
                ('preferencias', models.TextField(blank=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='public_workouts.publicworkoutaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publicworkoutprogram',
            name='authored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='public_workouts.publicworkoutprofessional'),
        ),
        migrations.CreateModel(
            name='PublicWorkoutMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='public_workouts.publicworkoutaccount')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='public_workouts.publicworkoutprofessional')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('account', 'version'), name='unique_meal_plan_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('account',), name='unique_active_meal_plan_per_account')],
            },
        ),
    ]
