# Generated by Django 6.0.8 on 2026-09-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_workouts", "0007_publicworkoutaccount_photo_url"),
        ("public_workouts", "0008_publicworkoutsubscription_plan_slug_nullable"),
    ]

    operations = []
