# Generated by Django 6.0.8 on 2026-09-18 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0010_seed_public_workout_professionals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWorkoutTrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(choices=[('hypertrophy', 'Hipertrofia'), ('strength', 'Força'), ('fat_loss', 'Emagrecimento'), ('general_health', 'Saúde geral'), ('athletic_performance', 'Performance esportiva')], max_length=32)),
                ('physical_restrictions', models.JSONField(blank=True, default=list)),
                ('physical_restrictions_detail', models.TextField(blank=True)),
                ('training_experience', models.CharField(choices=[('never_trained', 'Nunca treinou'), ('less_than_6_months', 'Menos de 6 meses'), ('6_months_to_2_years', 'De 6 meses a 2 anos'), ('more_than_2_years', 'Mais de 2 anos')], max_length=24)),
                ('days_per_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('training_location', models.CharField(choices=[('full_gym', 'Academia completa'), ('home_basic_equipment', 'Casa, com equipamento básico'), ('home_bodyweight_only', 'Casa, só peso do corpo'), ('outdoor_or_travel', 'Ao ar livre / viajando')], max_length=24)),
                ('motivation', models.TextField(blank=True)),
                ('biggest_difficulty', models.TextField(blank=True)),
                ('consent_ai_processing_at', models.DateTimeField(blank=True, null=True)),
                ('revalidated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_profile', to='public_workouts.publicworkoutaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicWorkoutProgramDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField()),
                ('source', models.CharField(choices=[('ai_generated', 'Gerado por IA'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Aguardando revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], db_index=True, default='pending_review', max_length=16)),
                ('training_profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=64)),
                ('generation_error', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_drafts', to='public_workouts.publicworkoutaccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending_review')), fields=('account', 'slug'), name='unique_pending_review_draft_per_account_slug')],
            },
        ),
    ]
