# Generated by Django 6.0.8 on 2026-09-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0009_merge_20260918_1537'),
        ('public_workouts', '0025_experiment_foundation'),
    ]

    operations = [
    ]
