# Generated by Django 6.0.8 on 2026-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0029_load_log_set_role_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutmovement',
            name='equipment_type',
            field=models.CharField(choices=[('barbell', 'Barra'), ('dumbbell', 'Halteres'), ('machine', 'Maquina'), ('bodyweight', 'Peso corporal'), ('cable', 'Cabo/polia'), ('other', 'Outro')], db_index=True, default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='publicworkoutmovement',
            name='logged_weight_includes_bar',
            field=models.BooleanField(default=False),
        ),
    ]
