# Generated by Django 6.0.8 on 2026-09-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0030_equipment_type_and_logged_weight_includes_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutloadlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='publicworkoutloadlog',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='public_workouts.publicworkoutloadlog'),
        ),
    ]
