# Generated by Django 6.0.8 on 2026-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0031_load_log_supersedes_and_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutloadlog',
            name='achievement_kind',
            field=models.CharField(blank=True, choices=[('load_record', 'Nova maior carga')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='publicworkoutloadlog',
            name='achievement_previous_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='publicworkoutloadlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('achievement_kind__isnull', True), ('achievement_previous_weight_kg__isnull', True)), models.Q(('achievement_kind__isnull', False), ('achievement_previous_weight_kg__isnull', False)), _connector='OR'), name='public_workouts_loadlog_achievement_kind_and_previous_weight_together'),
        ),
    ]
