# Generated by Django 6.0.8 on 2026-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0032_load_log_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutassessment',
            name='hero_commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
