# Generated by Django 6.0.8 on 2026-10-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0033_publicworkoutassessment_hero_commentary'),
        ('public_workouts', '0035_weekly_review_cache'),
    ]

    operations = [
    ]
