# Generated by Django 6.0.8 on 2026-10-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_workouts', '0036_merge_20260930_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicworkoutaccount',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
