# Generated by Django 6.0.3 on 2026-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('webhook_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_webhook_event',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='whatsapp_we_status_fed6fc_idx'), models.Index(fields=['webhook_fingerprint'], name='whatsapp_we_webhook_5bd474_idx')],
            },
        ),
    ]
