# Generated by Django 6.0.6 on 2026-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_paymentwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('charge_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('box_schema', models.CharField(db_index=True, max_length=63)),
                ('payment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'stripe_payment_ref',
                'ordering': ['-created_at'],
            },
        ),
    ]
