# Generated by Django 6.0.8 on 2026-10-01 22:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_stripepaymentref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='payload',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Payload bruto normalizado. Não expor fora de integrations/stripe/.'),
        ),
    ]
