# Generated by Django 6.0.3 on 2026-04-16 05:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxcore', '0019_financefollowup_suggestion_window_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExerciseMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_slug', models.SlugField(max_length=64)),
                ('exercise_label', models.CharField(max_length=120)),
                ('one_rep_max_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_maxes', to='boxcore.student')),
            ],
            options={
                'ordering': ['exercise_label'],
                'constraints': [models.UniqueConstraint(fields=('student', 'exercise_slug'), name='unique_student_exercise_max')],
            },
        ),
    ]
