# Generated by Django 6.0.3 on 2026-04-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0023_alter_asyncjob_status_alter_studentintake_source'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('coach_notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='boxcore.classsession')),
            ],
            options={
                'ordering': ['session__scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionWorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('warmup', 'Aquecimento'), ('strength', 'Forca'), ('skill', 'Skill'), ('metcon', 'Metcon'), ('cooldown', 'Cooldown'), ('custom', 'Livre')], default='custom', max_length=24)),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionWorkoutMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_slug', models.SlugField(max_length=64)),
                ('movement_label', models.CharField(max_length=120)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('load_type', models.CharField(choices=[('free', 'Livre'), ('fixed_kg', 'Carga fixa'), ('percentage_of_rm', 'Percentual do RM')], default='free', max_length=32)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='student_app.sessionworkoutblock')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
