# Generated by Django 6.0.3 on 2026-04-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workout_status(apps, schema_editor):
    SessionWorkout = apps.get_model('student_app', 'SessionWorkout')
    for workout in SessionWorkout.objects.all().only('id', 'is_published'):
        workout.status = 'published' if getattr(workout, 'is_published', False) else 'draft'
        workout.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_sessionworkout_sessionworkoutblock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionworkout',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workouts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workouts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workouts_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando aprovacao'), ('published', 'Publicado'), ('rejected', 'Rejeitado')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workouts_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_workout_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sessionworkout',
            name='is_published',
        ),
    ]
