# Generated by Django 6.0.3 on 2026-04-17 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_sessionworkout_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWorkoutRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event', models.CharField(choices=[('submitted', 'Enviado para aprovacao'), ('published', 'Publicado'), ('rejected', 'Rejeitado'), ('duplicated', 'Duplicado')], max_length=24)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workout_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
