# Generated by Django 6.0.3 on 2026-04-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0023_alter_asyncjob_status_alter_studentintake_source'),
        ('student_app', '0004_sessionworkoutrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkoutView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_viewed_at', models.DateTimeField()),
                ('last_viewed_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_views', to='boxcore.student')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_views', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['-last_viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'workout'), name='unique_student_workout_view')],
            },
        ),
    ]
