# Generated by Django 6.0.3 on 2026-04-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_studentworkoutview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWorkoutFollowUpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_key', models.CharField(max_length=64)),
                ('action_label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('completed', 'Resolvido'), ('dismissed', 'Descartado')], default='completed', max_length=24)),
                ('outcome_note', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workout_follow_up_actions_resolved', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_actions', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['-resolved_at', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('workout', 'action_key'), name='unique_workout_follow_up_action')],
            },
        ),
    ]
