# Generated by Django 6.0.3 on 2026-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_sessionworkoutfollowupaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionworkoutfollowupaction',
            name='baseline_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
