# Generated by Django 6.0.3 on 2026-04-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_sessionworkoutfollowupaction_baseline_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWorkoutOperationalMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reception_owned', 'Recepcao assumiu'), ('coach_aligned', 'Coach alinhado'), ('whatsapp_sent', 'WhatsApp disparado'), ('monitoring_note', 'Nota de monitoramento'), ('custom', 'Marco livre')], default='custom', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workout_operational_memories_created', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_memories', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
