# Generated by Django 6.0.3 on 2026-04-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_sessionworkoutoperationalmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWeeklyManagementCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(unique=True)),
                ('execution_status', models.CharField(choices=[('not_started', 'Nao iniciado'), ('in_progress', 'Em andamento'), ('completed', 'Concluido')], default='not_started', max_length=24)),
                ('responsible_role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('reception', 'Recepcao'), ('coach', 'Coach')], default='manager', max_length=24)),
                ('closure_status', models.CharField(blank=True, choices=[('worked', 'Funcionou'), ('partial', 'Parcial'), ('did_not_work', 'Nao funcionou')], max_length=24)),
                ('summary_note', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_weekly_management_checkpoints_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', '-updated_at', '-id'],
            },
        ),
    ]
