# Generated by Django 6.0.3 on 2026-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_workoutweeklymanagementcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutweeklymanagementcheckpoint',
            name='governance_commitment_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workoutweeklymanagementcheckpoint',
            name='governance_commitment_status',
            field=models.CharField(choices=[('not_assumed', 'Nao assumido'), ('assumed', 'Assumido'), ('executed', 'Executado')], default='not_assumed', max_length=24),
        ),
    ]
