# Generated by Django 6.0.3 on 2026-04-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_workoutweeklymanagementcheckpoint_governance_commitment_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionWorkoutRmGapAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('exercise_slug', models.SlugField(max_length=64)),
                ('exercise_label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('requested', 'RM solicitado'), ('collected', 'RM coletado'), ('free_load', 'Deixar carga livre')], default='requested', max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_workout_rm_gap_actions', to='boxcore.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_workout_rm_gap_actions_updated', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_gap_actions', to='student_app.sessionworkout')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('workout', 'student', 'exercise_slug'), name='unique_workout_student_rm_gap_action')],
            },
        ),
    ]
