# Generated by Django 6.0.3 on 2026-04-23 13:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0023_alter_asyncjob_status_alter_studentintake_source'),
        ('student_app', '0012_alter_sessionworkoutrmgapaction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('attendance_confirmed', 'Presenca confirmada'), ('wod_viewed', 'WOD aberto'), ('rm_created', 'RM criado'), ('rm_updated', 'RM atualizado')], max_length=32)),
                ('activity_date', models.DateField()),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_app_activities', to='boxcore.student')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'activity_date'], name='student_activity_day_lookup'), models.Index(fields=['student', 'kind', 'activity_date'], name='student_activity_kind_day')],
            },
        ),
        migrations.CreateModel(
            name='StudentExerciseMaxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_slug', models.SlugField(max_length=64)),
                ('exercise_label', models.CharField(max_length=120)),
                ('previous_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('source', models.CharField(default='student_app', max_length=32)),
                ('exercise_max', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='student_app.studentexercisemax')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_max_history', to='boxcore.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'exercise_slug', '-created_at'], name='student_rm_history_lookup')],
            },
        ),
    ]
