# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_identity', '0005_studentappinvitation_invite_type'),
        ('student_app', '0013_studentappactivity_studentexercisemaxhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='student_identity.studentidentity')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile_change_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='boxcore.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'status', '-created_at'], name='student_profile_request_lookup')],
            },
        ),
    ]
