# Generated by Django 6.0.3 on 2026-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_sessionworkout_replication_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionworkout',
            name='is_normalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionworkout',
            name='structured_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
