# Generated by Django 6.0.3 on 2026-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0018_sessionworkout_smartplan_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label_pt', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('reference_url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Biblioteca de Movimento',
                'verbose_name_plural': 'Biblioteca de Movimentos',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterField(
            model_name='workoutweeklymanagementcheckpoint',
            name='execution_status',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído')], default='not_started', max_length=24),
        ),
        migrations.AlterField(
            model_name='workoutweeklymanagementcheckpoint',
            name='governance_commitment_status',
            field=models.CharField(choices=[('not_assumed', 'Não assumido'), ('assumed', 'Assumido'), ('executed', 'Executado')], default='not_assumed', max_length=24),
        ),
    ]
