# Generated by Django 6.0.8 on 2026-09-02 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0019_movementlibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicationbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_wod_replication_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkout',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workouts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workouts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkout',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workouts_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkout',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workouts_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkoutfollowupaction',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workout_follow_up_actions_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkoutoperationalmemory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workout_operational_memories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkoutrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workout_revisions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionworkoutrmgapaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_workout_rm_gap_actions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofilechangerequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_profile_change_requests_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklywodplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_wod_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutweeklymanagementcheckpoint',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_weekly_management_checkpoints_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
