# Generated by Django 6.0.8 on 2026-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0022_wod_prescription_fidelity'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationbatch',
            name='idempotency_key',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='replicationbatch',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicationbatch',
            name='target_week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
