# Generated by Django 6.0.8 on 2026-09-28 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcore', '0031_workout_program_tracks'),
        ('student_app', '0023_replicationbatch_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklywodplan',
            name='workout_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_wod_plans', to='boxcore.workoutprogram'),
        ),
        migrations.AddIndex(
            model_name='weeklywodplan',
            index=models.Index(fields=['workout_program', 'week_start'], name='weekly_wod_program_week'),
        ),
    ]
