# Generated by Django 6.0.8 on 2026-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0024_workout_program_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlibrary',
            name='demo_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
