# Generated by Django 6.0.3 on 2026-05-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_workouttemplate_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlanGateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('canonical_published', 'Canonico publicado diretamente'), ('canonical_pending', 'Canonico enviado para aprovacao'), ('invalid_popup', 'Invalido — popup exibido'), ('raw_confirmed', 'Cru confirmado pelo coach'), ('empty_paste', 'Paste vazio')], db_index=True, max_length=24)),
                ('session_id', models.PositiveIntegerField(db_index=True)),
                ('paste_length', models.PositiveIntegerField(blank=True, null=True)),
                ('block_count', models.PositiveIntegerField(blank=True, null=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=32)),
                ('prompt_version', models.CharField(blank=True, default='v1.0.0', max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartplan_gate_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outcome', 'created_at'], name='ops_sp_gate_outcome_idx'), models.Index(fields=['session_id', 'created_at'], name='ops_sp_gate_sess_idx')],
            },
        ),
    ]
