# Generated by Django 6.0.8 on 2026-09-02 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_smartplangateevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplangateevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='smartplan_gate_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutapprovalpolicysetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_approval_policies_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplannertemplatepickerevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_planner_template_picker_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_templates_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_templates_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
