# Generated by Django 6.0.4 on 2026-05-08 21:42

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('slug', models.SlugField(max_length=59, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('provisioning', 'Provisionando'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], db_index=True, default='provisioning', max_length=16)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('plan', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('cell', models.CharField(db_index=True, default='cell-1', max_length=32)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_boxes', to=settings.AUTH_USER_MODEL)),
                ('pending_signup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box', to='signup.pendingsignup')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxProvisioningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_events', to='control.box')),
            ],
            options={
                'verbose_name': 'BoxProvisioningEvent',
                'verbose_name_plural': 'BoxProvisioningEvents',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='control.box')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Recepção')], max_length=16)),
                ('is_primary_box', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='control.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to='control.box')),
            ],
            options={
                'verbose_name': 'PlatformAuditEvent',
                'verbose_name_plural': 'PlatformAuditEvents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['status', 'cell'], name='control_box_status_dc87b8_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['stripe_subscription_id'], name='control_box_stripe__6e6b69_idx'),
        ),
        migrations.AddIndex(
            model_name='boxprovisioningevent',
            index=models.Index(fields=['box', 'step', 'status'], name='control_box_box_id_e58443_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_primary_box'], name='control_mem_user_id_4364a0_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['box', 'role'], name='control_mem_box_id_9268b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'box')},
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['kind', '-created_at'], name='control_pla_kind_c1d8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['target_box', '-created_at'], name='control_pla_target__8ba37c_idx'),
        ),
    ]
