# Generated by Django 6.0.7 on 2026-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_box_billing_event_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Recepção'), ('dev', 'DEV (suporte)')], max_length=16),
        ),
    ]
