name: Load Tests - Import

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Host da aplicação (ex: http://127.0.0.1:8000)'
        required: true
        default: 'http://127.0.0.1:8000'
      user:
        description: 'Usuário de teste'
        required: true
        default: 'admin'
      pass:
        description: 'Senha de teste'
        required: true
        default: 'admin'
      csv_file:
        description: 'Nome do arquivo CSV em load_tests (ex: students_seed_50k.csv)'
        required: true
        default: 'students_seed_50k.csv'

jobs:
  run-k6-import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run k6 import test (docker)
        run: |
          docker run --rm -v ${{ github.workspace }}:/scripts -e HOST=${{ github.event.inputs.host }} -e TEST_USER=${{ github.event.inputs.user }} -e TEST_PASS=${{ github.event.inputs.pass }} -e CSV_FILE=${{ github.event.inputs.csv_file }} loadimpact/k6 run --summary-export=/scripts/load_tests/summary_import.json /scripts/load_tests/k6_multipart_import.js

      - name: Upload k6 import summary
        uses: actions/upload-artifact@v7
        with:
          name: k6-import-summary
          path: load_tests/summary_import.json
